version: '3.8'

services:
  mongodb:  
    image: mongo:latest  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/data/db  
    networks:  
      - hdp-network  
    healthcheck:  
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]  
      interval: 10s  
      timeout: 5s  
      retries: 5  
      start_period: 30s  

  # ===========================================================================
  # SERVICE WEB DJANGO
  # ===========================================================================
  web:
    build: .
    container_name: django-web
    ports:
      - "8001:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MONGODB_HOST=mongodb
      - ATLAS_URL=http://172.19.0.2:21000
      - ATLAS_USERNAME=admin
      - ATLAS_PASSWORD=ensias123
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
      - KAFKA_ENABLED=true
    volumes:
      - .:/app
    networks:
      - hdp-network
      - kafka-integration

  # ===========================================================================
  # KAFKA CONSUMER - SERVICE CORRIGÉ
  # ===========================================================================
  kafka-consumer:
    build: .
    container_name: django-kafka-consumer
    depends_on:
      - mongodb
      - web
    env_file:
      - .env
    environment:
      - MONGODB_HOST=mongodb
      - ATLAS_URL=http://172.19.0.2:21000
      - ATLAS_USERNAME=admin
      - ATLAS_PASSWORD=ensias123
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
      - KAFKA_CONSUMER_GROUP=django-governance-group
      - KAFKA_ENABLED=true
    volumes:
      - .:/app
    networks:
      - hdp-network
      - kafka-integration
    # CORRECTION CRITIQUE: Lancer le consumer Kafka, pas Django
    command: ["python", "manage.py", "start_kafka_consumer"]
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  hdp-network:
    driver: bridge
  kafka-integration:
    external: true
    name: kafka-integration-network